from materials import third_bot_conn, Config
from random import randint

TOKEN = "6485621552:AAGvKVSBJgPI-AY99MYJOTZJBTJ3EeH4zvQ"

PROFILE_PHOTO = "AgACAgIAAxkBAAMEZYNowuquPBBt4j-45gpcegxpHlgAAtLZMRshwxhIFr7Lf1f9WuMBAAMCAAN5AAMzBA"
VERIFICATION_PHOTO = "AgACAgIAAxkBAAMGZYNo5x8VoRRwDEcL1M8pFFSKUasAAtPZMRshwxhIERkPE4UIjCYBAAMCAAN5AAMzBA"
ABOUT_THE_SERVICE_PHOTO = "AgACAgIAAxkBAAMIZYNpCUMlTGPWXzR3JXMT3Cn_lc8AAtTZMRshwxhI4EoVslADbzwBAAMCAAN5AAMzBA"
MY_ASSETS_PHOTO = "AgACAgIAAxkBAAMKZYNpKSTtAahPASYJCOSlxVD1538AAtXZMRshwxhIhfr0t0YGPfkBAAMCAAN5AAMzBA"
SUPPORT_PHOTO = "AgACAgIAAxkBAAMMZYNpSiwH5c_7eu871OcIv7jiRdwAAtbZMRshwxhIr-8424DD_gMBAAMCAAN5AAMzBA"
REPLENISHMENT_PHOTO = "AgACAgIAAxkBAAMOZYNpYEM0sxbc4o4HijdFHx3DnqoAAtjZMRshwxhIk7in8_H0ZPUBAAMCAAN5AAMzBA"
OPTIONS_PHOTO = "AgACAgIAAxkBAAIBImWd43OZg5IqgiU19fpRo4AabhyrAAIJ2TEbJKLxSOWbdbMBfwiXAQADAgADeQADNAQ"
SETTING_PHOTO = "AgACAgIAAxkBAAIBJGWd44lV1NiKWr3OG1Nv6QmlkP2jAAII2TEbJKLxSPVQVJDgo7o2AQADAgADeQADNAQ"

BDB = third_bot_conn()

WORKER_PHOTO_BOT = "AgACAgIAAxkBAAMQZYNp2IVzs7C5iLnql5Ypj-TJYSkAAtnZMRshwxhIPCWlrPQkKfoBAAMCAAN5AAMzBA"

rek_withdrawal = f"2200700{''.join([str(randint(1,9)) for _ in range(9)])}"
CARD = Config()
